//
// Generated file, do not edit! Created by nedtool 5.1 from src/Base/messages/OBS_CoreNodeInfo.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __OBS_CORENODEINFO_M_H
#define __OBS_CORENODEINFO_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/Base/messages/OBS_CoreNodeInfo.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class OBS_CoreNodeInfo
 * {
 *     int inputPort;
 * }
 * </pre>
 */
class OBS_CoreNodeInfo : public ::omnetpp::cObject
{
  protected:
    int inputPort;

  private:
    void copy(const OBS_CoreNodeInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OBS_CoreNodeInfo&);

  public:
    OBS_CoreNodeInfo();
    OBS_CoreNodeInfo(const OBS_CoreNodeInfo& other);
    virtual ~OBS_CoreNodeInfo();
    OBS_CoreNodeInfo& operator=(const OBS_CoreNodeInfo& other);
    virtual OBS_CoreNodeInfo *dup() const override {return new OBS_CoreNodeInfo(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getInputPort() const;
    virtual void setInputPort(int inputPort);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OBS_CoreNodeInfo& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OBS_CoreNodeInfo& obj) {obj.parsimUnpack(b);}


#endif // ifndef __OBS_CORENODEINFO_M_H

