//@titlepage
// <center><h1>Flexi-OBS Modules for OMNeT++/OMNEST</h1></center>
// <center>release 2013-01-14</center>
//
//
// Flexi-OBS Modules implements all basic components required to simulate flex-spectrum OBS networks. Functionalities are isolated over submodules in order to keep it as modular as possible.
//
// A complete OBS network architecture can be represented as follows:

package flexi_obsmodules;

@license(LGPL);
